variables

diff --git a/09-install-mysql b/09-install-mysql
--- a/09-install-mysql
+++ b/09-install-mysql
@@ -5,8 +5,18 @@ ID=$(id -u)
 if [ $ID -ne 0 ]
 then
 echo "Error:please run with root user"
+exit 1
 else
 echo "you are root user"
 fi
 
 yum install mysql -y
+
+if($? -ne 0)
+then
+echo "Error:installing mysql failed"
+exit 1
+else
+echo " installling mysql is sucess"
+fi
+
